### ISSUE TITLE
KnexTimeoutError: Knex: Timeout acquiring a connection.

### ISSUE THREAD

**Issue by jeonjonghyeok** [ChihChengLiang/semaphore_auth#25]
```
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/Users/jonghyeokjeon/ethereum/semaphore_auth/packages/backend/node_modules/knex/lib/client.js:347:26)
    at async bindDb (/Users/jonghyeokjeon/ethereum/semaphore_auth/packages/backend/src/app.js:14:3)
    at async main (/Users/jonghyeokjeon/ethereum/semaphore_auth/packages/backend/index.js:4:3) {
  sql: 'select 1+1 as result',
  bindings: undefined
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jeonjonghyeok** [comment]
It's a version issue with the backend node module.
If I modify the version like this it works fine.

```
package.json
"knex": "^0.21.1",
"objection": "^2.1.3",
"pg": "^8.0.3"
```

https://stackoverflow.com/questions/40435315/knex-timeout-acquiring-a-connection-the-pool-is-probably-full-are-you-missing
